ProjectName: 'TestProject'  # 项目名称

# 服务器配置
ServerConfig:
  host: '0.0.0.0'  # 主机
  port: 7878  # 端口
  workers: 1  # 进程数
  log_dir: 'logs'  # 日志目录路径
  file_max_size: 3145728  # 文件最大上传大小（字节）
  token_expire: 604800  # Token有效期（秒），用户登录有效期
  secret_key: "93b0da7c01a615a5ec93d1ce0048e440"  # Token密钥

  # 跨域配置
  CORSConfig:
    allow_origins: ['*']
    allow_methods: ['*']
    allow_headers: ['*']

# 邮箱配置
EmailConfig:
  email_from: 'xxx@163.com'  # 发件邮箱
  email_password: 'XXX'  # 邮箱密码/SMTP授权码
  email_code_expire: 300  # 邮箱验证码有效期（秒）

# 数据库配置
DatabaseConfig:
  # Mysql配置
  MysqlConfig:
    host: '127.0.0.1'  # 主机
    port: 3306  # 端口
    database_name: 'test_project'  # 数据库名称
    username: 'root'  # 用户名
    password: 'root'  # 密码
    auto_create_table: false  # 是否自动创建表

  # Redis配置
  RedisConfig:
    host: '127.0.0.1'  # 主机
    port: 6379  # 端口
    password: '' # 密码
    db: 6  # 数据库
